# Generated by Django 3.1 on 2020-08-25 03:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=50)),
                ('wondrous', models.BooleanField(default=False)),
                ('requires_attunement', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArmorTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_name', models.CharField(max_length=30)),
                ('trait_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=140)),
                ('item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_management.armor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('text_description', models.TextField()),
                ('lore', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.TextField(verbose_name=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attunement_slots', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=3)])),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity_level', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_name', models.CharField(max_length=30)),
                ('trait_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=140)),
                ('weapon_type', models.CharField(blank=True, choices=[('Special', 'Special'), ('Either', 'Either'), ('Melee', 'Melee'), ('RANGED', 'Ranged')], default=None, max_length=10)),
                ('item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_management.armor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=50)),
                ('wondrous', models.BooleanField(default=False)),
                ('requires_attunement', models.BooleanField(default=False)),
                ('damage', models.TextField(verbose_name=35)),
                ('range', models.TextField(default=None, verbose_name=30)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_management.description')),
                ('item_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_management.itemslot')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_management.player')),
                ('rarity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_management.rarity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=125)),
                ('level', models.SmallIntegerField()),
                ('armor_trait', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='item_management.armortrait')),
                ('weapon_trait', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='item_management.weapontrait')),
            ],
        ),
        migrations.AddField(
            model_name='armor',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_management.description'),
        ),
        migrations.AddField(
            model_name='armor',
            name='item_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_management.itemslot'),
        ),
        migrations.AddField(
            model_name='armor',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_management.player'),
        ),
        migrations.AddField(
            model_name='armor',
            name='rarity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_management.rarity'),
        ),
    ]
