# Generated by Django 3.1 on 2020-08-26 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='attunement_slots',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(limit_value=3)]),
        ),
    ]
