# Generated by Django 3.1 on 2020-08-28 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0003_auto_20200825_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rarity',
            options={'verbose_name_plural': 'Rarities'},
        ),
        migrations.RemoveField(
            model_name='tier',
            name='armor_trait',
        ),
        migrations.RemoveField(
            model_name='tier',
            name='weapon_trait',
        ),
        migrations.AddField(
            model_name='armortrait',
            name='tier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='item_management.tier'),
        ),
        migrations.AddField(
            model_name='weapontrait',
            name='tier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='item_management.tier'),
        ),
    ]
