# Generated by Django 3.1 on 2020-08-28 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0005_auto_20200827_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='item_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item_management.itemslot'),
        ),
        migrations.AlterField(
            model_name='itemslot',
            name='slot_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='item_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item_management.itemslot'),
        ),
    ]
