# Generated by Django 3.1 on 2020-08-28 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0006_auto_20200827_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='item_type',
        ),
    ]
