# Generated by Django 3.1 on 2020-08-28 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0007_auto_20200827_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='item_management.description'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='item_management.description'),
        ),
    ]
