# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: master
  
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v2

     # Runs a set of commands using the runners shell
    - name: Install Dependencies
      run: |
        echo Installing
        cd /home/runner/work/aftermath/aftermath/aftermath-react
        npm install
        
    - name: Build Project
      run: |
        echo Building
        cd /home/runner/work/aftermath/aftermath/aftermath-react
        npm run build
      
      # Prep workspace for branch swap
    - name: Clean workspace
      run: |
        cd /home/runner/work/aftermath/aftermath/aftermath-react
        cp -r build/* ../
        rm -rf *
        rm -rf src/
        rm -f *
        cd ..
      # push changes to branch page
    - name: Publish
      run: |
        date > generated.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch
        cd /home/runner/work/aftermath/aftermath/
        git checkout -b page
        git add -- . ':!aftermath-react'
        git commit -m "generated"
        git push --force origin page
        
       
     
    
